### ISSUE TITLE
建议优化

### ISSUE THREAD

**Issue by huanlu233** [keiko233/elaina-theme-netease#35]
![image](https://github.com/keiko233/elaina-theme-netease/assets/100133765/063debb5-86fd-4d08-a4f5-fa87ad67a0c8)
在开启半透明框架后搜索页成黑色，无法看清文字，如果不开起，发现音乐将会出现白条
![image](https://github.com/keiko233/elaina-theme-netease/assets/100133765/5d640061-1925-4f6a-b76b-055d4d49b5ee)
建议尽快修复或优化

**Comment by keiko233** [comment]
1. fixed
2. 网易云的锅，开启半透明会自动修正
