### ISSUE TITLE
与RefinedNowPlaying插件同时使用时，歌词界面布局错误

### ISSUE THREAD

**Issue by Izayoi9** [keiko233/elaina-theme-netease#38]
与RefinedNowPlaying插件同时使用时，在歌词界面下，歌曲封面与歌词重叠
![image](https://github.com/keiko233/elaina-theme-netease/assets/105905446/1159d76e-e3ba-4598-8596-ec09e95fac26)
![image](https://github.com/keiko233/elaina-theme-netease/assets/105905446/d33e1f28-ba68-4dcb-b59b-7d42dc0ecc76)
随后，我尝试关闭伊蕾娜插件的播放器样式
![image](https://github.com/keiko233/elaina-theme-netease/assets/105905446/759e8e9e-374a-400f-82a5-114fefeb77af)
此时歌曲播放页面顶部出现了顶栏。
![image](https://github.com/keiko233/elaina-theme-netease/assets/105905446/b97fd16a-4228-401f-a455-9aa1927b8c77)
希望能解决该问题

**Comment by Izayoi9** [comment]
刚才发现关闭“启用半透明框架”功能后，歌曲播放页面的顶栏消失
![image](https://github.com/keiko233/elaina-theme-netease/assets/105905446/523affb4-58e2-4402-a961-0005f1684739)
![image](https://github.com/keiko233/elaina-theme-netease/assets/105905446/749bb60c-db8f-4ce0-9a56-ddb41e03ca5c)

**Comment by keiko233** [comment]
fixed.
