### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by GOOLDOVE** [keiko233/elaina-theme-netease#39]
大佬能不能把2.9版本那个白色字体弄回来啊QWQ，那个是真的好看
![image](https://github.com/keiko233/elaina-theme-netease/assets/81006632/f38534ce-fe9b-4e5f-8633-811c12d39de3)

**Comment by keiko233** [comment]
ok

**Comment by keiko233** [comment]
https://github.com/keiko233/elaina-theme-netease/commit/4cfab2230954f81734299a13fd87bcb6927e40a5
