### ISSUE TITLE
【Bug反馈】关于自定义背景始终无法生效的反馈

### ISSUE THREAD

**Issue by Sakura1213866138** [keiko233/elaina-theme-netease#40]
现象：
1、最新版本的伊蕾娜主题在我的电脑上始终无法使用自定义图片功能，如果自己上传，不论横竖或者大小都会不能生效，表现是不能预览且没有反应。
2、每次启动拉取的图片有可能是竖屏的，导致放大后非常不美观。
期望：
1、使自定义背景图片可定义、可预览。
2、内置一部分伊蕾娜的横版图片，可以按照自己的选择轮换或者不轮换。
感谢作者制作了这个主题，如果能修复这个问题那就更好了

**Comment by keiko233** [comment]
好的，有空了我看看

**Comment by Sakura1213866138** [comment]
好耶，感谢作者大大

**Comment by keiko233** [comment]
1. https://github.com/keiko233/elaina-theme-netease/commit/ff24f27c54709088cb026abad1e7083fd31ff35f
2. https://github.com/keiko233/elaina-theme-netease/commit/7f9c1a2b76e8af1d2a8686ac37cac0f2d5188011
