### ISSUE TITLE
【BUG】消息组件被遮挡

### ISSUE THREAD

**Issue by youyou-sudo** [keiko233/elaina-theme-netease#45]
点击消息无法显示消息列表
<img width="353" alt="image" src="https://github.com/keiko233/elaina-theme-netease/assets/60727068/67ab2960-7ea4-42de-8a87-9ae92712111a">

**Comment by keiko233** [comment]
已修复，下个版本更新，可以自行到actions下载开发构建版本安装，https://github.com/keiko233/elaina-theme-netease/commit/ebed8b641664d0edf6ba647bd0c39ac0d0669f01 https://github.com/keiko233/elaina-theme-netease/actions/runs/5770580212
