### ISSUE TITLE
建议增加每日背景图类型选择选项，可以选择波奇或者伊蕾娜之类的，

### ISSUE THREAD

**Issue by GoogleNB** [keiko233/elaina-theme-netease#47]
这几天似乎api图片类型多起来了，不想设置不认识的角色每日随机。
![VL CC0}}VSLI JR%M{L0F92](https://github.com/keiko233/elaina-theme-netease/assets/42306741/189241ed-6b8b-4fd2-bad0-56e0ef80638e)

**Comment by keiko233** [comment]
https://github.com/keiko233/elaina-theme-netease/commit/7ea96581b5ca99d613eb9bebe364af45df0fd20b
