### ISSUE TITLE
【精简】希望可以自定义精简内容

### ISSUE THREAD

**Issue by cale044** [keiko233/elaina-theme-netease#5]
照顾一下平常会看评论区人吧

**Comment by keiko233** [comment]
重构版已加回来，可以在actions里下载到，自定义功能还在写

**Comment by cale044** [comment]
还是直接发Releases吧

**Comment by keiko233** [comment]
自动编译不发releases，而且官方插件的收录方法也不是走releases，开发需要遵守官方的方法

**Comment by cale044** [comment]
但是我觉得好麻烦唉

**Comment by keiko233** [comment]
https://github.com/keiko233/elaina-theme-netease/actions/runs/4192753427

下载output-dist 修改后缀为plugin，不难吧

**Comment by cale044** [comment]
> https://github.com/keiko233/elaina-theme-netease/actions/runs/4192753427
> 
> 下载output-dist 修改后缀位plugin，不难吧

ok
