### ISSUE TITLE
点击消息图标没有反应

### ISSUE THREAD

**Issue by syf1447** [keiko233/elaina-theme-netease#50]
网易云音乐版本2.10.12（Build:201849）(Patch:1:62cafa
7)
BatterNCM版本1.3.0
主题版本1.0.5
![111](https://github.com/keiko233/elaina-theme-netease/assets/128719053/410f1551-32e2-4056-9450-eb5c82ee859f)

**Comment by keiko233** [comment]
无法复现且该问题曾已修复 https://github.com/keiko233/elaina-theme-netease/issues/45 并合并到main，请检查其他插件兼容性问题

**Comment by syf1447** [comment]
关闭启用半透明框架后点击消息图标正常
![3](https://github.com/keiko233/elaina-theme-netease/assets/128719053/4d369f6f-de45-4070-a374-2589db197fd6)

**Comment by keiko233** [comment]
emmm，有空我再看看
