### ISSUE TITLE
启动毛玻璃效果 主题边框设置0以上 主页歌曲封面是全红的

### ISSUE THREAD

**Issue by CooStack** [keiko233/elaina-theme-netease#51]
目前设置
![image](https://github.com/keiko233/elaina-theme-netease/assets/112278452/484cf7e3-da6f-4e56-83ae-835a6c657787)
效果
![image](https://github.com/keiko233/elaina-theme-netease/assets/112278452/c56b2d0b-1355-4d6a-8259-c81a34ad70cd)

修改主页边框
![image](https://github.com/keiko233/elaina-theme-netease/assets/112278452/f8569007-f9d5-40d1-88b6-b2ecb9f46982)
bug
![image](https://github.com/keiko233/elaina-theme-netease/assets/112278452/c33b136b-5170-4cf5-bbfd-2d8f63a51d34)

**Comment by keiko233** [comment]
没有复现出来，请检查是不是其他插件冲突的问题
