### ISSUE TITLE
自定义背景一直在加载中

### ISSUE THREAD

**Issue by xiaoyangsheyuan** [keiko233/elaina-theme-netease#52]
![image](https://github.com/keiko233/elaina-theme-netease/assets/128885875/7d2646d9-8a2e-46d7-98ad-75cd54086b4c)

固定用了几天了，然后就一直在加载

**Comment by keiko233** [comment]
检查 https://pic.majokeiko.com/help.html 是否可以打开，不能打开则可能是网络的问题

**Comment by xiaoyangsheyuan** [comment]
> 检查 https://pic.majokeiko.com/help.html 是否可以打开，不能打开则可能是网络的问题

可以打开，现在背景图片回来了，还是加载中
![image](https://github.com/keiko233/elaina-theme-netease/assets/128885875/f6e65703-7f3c-495f-b1aa-f86bf2d8f399)

**Comment by keiko233** [comment]
奇怪了，可以尝试重载
