### ISSUE TITLE
主题背景一直加载

### ISSUE THREAD

**Issue by Olucia02** [keiko233/elaina-theme-netease#54]
如题，根据其他issues的反馈，感觉可能是服务器炸了，那个网址进不去，已知联网没问题，也试过挂梯子
![Uploading U2B18LRMZ8@~UO$$46JQ}RL.png…]()
![Uploading [VMFN1MUCIXX2O(18LX~F`0.png…]()

**Comment by Olucia02** [comment]
![VMFN1MUCIXX2O(18LX~F`0](https://github.com/keiko233/elaina-theme-netease/assets/127415631/0c5a0408-b60f-476b-a4f5-4c7309b1e698)
![U2B18LRMZ8@~UO$46JQ}RL](https://github.com/keiko233/elaina-theme-netease/assets/127415631/174d7a4b-4e51-4e9f-94fa-0465e35fdde2)

**Comment by keiko233** [comment]
服务器挂了，修复时间未知…

**Comment by Olucia02** [comment]
> 服务器挂了，修复时间未知…

好的，谢谢，辛苦了

**Comment by keiko233** [comment]
> > 服务器挂了，修复时间未知…
> 
> 好的，谢谢，辛苦了

已恢复
